<script type="text/javascript">
<?= Asset::js('js', 'EventEmitter.js'); ?>
<?= Asset::js('js', 'Loader.src.js'); ?>
<?= Asset::js('js', 'Tween.src.js'); ?>
<?= Asset::js('js', 'FrameUpdate.js'); ?>
<?= Asset::js('js', 'FrameAnimation.src.js'); ?>
<?= Asset::js('js', 'Dom.js'); ?>
<?= Asset::js('js', 'Log.js'); ?>
<?= Asset::js('js', 'beautify.js'); ?>
<?= Asset::js('js', 'cms/common.js'); ?>
<?= Asset::js('js', 'cms/lightbox.js'); ?>
<?= Asset::js('js', 'cms/user.js'); ?>
<?= Asset::js('js', 'cms/imagebox.js'); ?>
<?= Asset::js('js', 'cms/nicEdit.js'); ?>
<?= Asset::js('js', 'cms/block.js'); ?>
<?= Asset::js('js', 'cms/calendar.js'); ?>
<?= Asset::js('js', 'cms/textEditor.js'); ?>
<?= Asset::js('js', 'cms/mediabox.js'); ?>
<?= Asset::js('js', 'cms/tableDataBuilder.js'); ?>
</script>
